default: &default
  adapter: postgresql
  database: mje_development
  encoding: UTF8
  port: 5432
  host: localhost
  min_messages: warning
  pool: <%= ENV['DATABASE_POOL'] || 5 %>

development:
  <<: *default

test:
  <<: *default
  database: mje_test

production:
  <<: *default
  pool:  <%= ENV['DATABASE_POOL'] || 5 %>
  database: mje_test
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
